V1.2 , Online Game UI refactor
svetlichnyiMaxim/9-men.s-morris-engine pull request #5
Opened 2024-10-09 06:44 UTC by postal398

A lot of UI addings

2024-11-14 10:50 UTC, kroune requested changes

2024-11-14 10:50 UTC, kroune commented on app/build.gradle.kts
> +    implementation(libs.androidx.foundation.android)
зачем нужна эта зависимость? Думаю, что можно её убрать

2024-11-14 10:50 UTC, kroune commented on app/src/main/kotlin/com/kroune/nineMensMorrisApp/NavHost.kt
> +            RenderLeaderboardScreen(vm.players, resources = context.resources,)
- убери "," в конце
- лучше либо поставить везде название переменной, либо везде убрать (я говорю про resources = ...)

2024-11-14 10:50 UTC, kroune commented on app/src/main/kotlin/com/kroune/nineMensMorrisApp/ui/impl/OnlineLeaderboardScreen.kt
> +
убери лишние пустые строки

2024-11-14 10:50 UTC, kroune commented on app/src/main/kotlin/com/kroune/nineMensMorrisApp/ui/impl/OnlineLeaderboardScreen.kt
> +        )
используй stickyHeader (и тогда соответственно убери лишний Column)

2024-11-14 10:50 UTC, kroune commented on app/src/main/kotlin/com/kroune/nineMensMorrisApp/ui/impl/OnlineLeaderboardScreen.kt
> +//            color = Color.White
удали эту строчку раз она не нужна (и не является комментарием)

2024-11-14 10:50 UTC, kroune commented on app/src/main/kotlin/com/kroune/nineMensMorrisApp/ui/impl/OnlineLeaderboardScreen.kt
> +//            .fillMaxHeight()
и эту строчку тоже удали

2024-11-14 10:50 UTC, kroune commented on app/src/main/kotlin/com/kroune/nineMensMorrisApp/ui/impl/OnlineLeaderboardScreen.kt
> +        LazyColumn (/*modifier = modifier.fillMaxHeight()*/) {
удали закомменченную часть

2024-11-14 10:50 UTC, kroune commented on app/src/main/kotlin/com/kroune/nineMensMorrisApp/ui/impl/OnlineLeaderboardScreen.kt
> +            modifier = Modifier.padding(16.dp)/*.background(Color.LightGray)*/
тоже удали коммент

2024-11-14 10:50 UTC, kroune commented on app/src/main/kotlin/com/kroune/nineMensMorrisApp/ui/impl/OnlineLeaderboardScreen.kt
> +                    player.pictureByteArray.value?.size!!
зачем нужен "?" если дальше ставишь "!!"

2024-11-14 10:50 UTC, kroune commented on app/src/main/kotlin/com/kroune/nineMensMorrisApp/ui/impl/OnlineLeaderboardScreen.kt
> +                )} else {
тут форматинг немного полетел

2024-11-14 10:50 UTC, kroune commented on app/src/main/kotlin/com/kroune/nineMensMorrisApp/ui/impl/game/OnlineGameScreen.kt
> +//            .fillMaxWidth(0.5f)
удали этот коммент

2024-11-14 10:50 UTC, kroune commented on app/src/main/kotlin/com/kroune/nineMensMorrisApp/viewModel/impl/LeaderboardViewModel.kt
> + * welcome model
обнови документацию

2024-11-14 10:50 UTC, kroune commented on app/src/main/kotlin/com/kroune/nineMensMorrisApp/viewModel/impl/LeaderboardViewModel.kt
> +                            accountRating = userInfoUseCase.accountRating// ?: 0L
удали закомментированную часть

2024-11-15 13:37 UTC, postal398 commented on app/build.gradle.kts
> +    implementation(libs.androidx.foundation.android)
Видимо, автоимпорт при экспериментах. Убрал

2024-11-15 13:43 UTC, postal398 commented on app/src/main/kotlin/com/kroune/nineMensMorrisApp/NavHost.kt
> +            RenderLeaderboardScreen(vm.players, resources = context.resources,)
убрал, подобавлял везде resources =

2024-11-18 17:16 UTC, kroune commented on app/src/main/kotlin/com/kroune/nineMensMorrisApp/NavHost.kt
> +            SearchingForGameScreen(expectedWaitingTime,resources = context.resources)
добавь пробел между , и resources

2024-11-18 18:10 UTC, merged